title:
description: Get your initial and recurring Pilot Flight Training with Dakota Wings

client:
  name:
  about_markdown: |
    When things happen - enjoy them. They're little gifts. In this world, everything can be happy. All you have to do is let your imagination go wild. Look around. Look at what we have. Beauty is everywhere you only have to look to see it.

    There is immense joy in just watching - watching all the little creatures in nature. Don't be afraid to make these big decisions. Once you start, they sort of just make themselves. These things happen automatically. All you have to do is just let them happen.
  brand: Dakota Wings
  address: 123 Sesame Street<br>Omaha, Nebraska 68132
  phone: 123-456-7890
  email: example@email.com
  url:

socials:
  review_sm_icons: false
  facebook_url:
  linkedin_url:
  gplus_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  podcast_url:


images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text:
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg

site_colors:
  brand_color: '#50c6d1'
  theme_color: '#0b1b1f'
  accent_color: '#e17146'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: '#443248'

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
